# Generated by Django 2.2.3 on 2019-07-28 13:18

import character.models.mixins.wellbeing_mixin
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chronicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('concept', models.TextField()),
                ('ambition', models.TextField()),
                ('desire', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField(blank=True)),
                ('true_age', models.PositiveIntegerField()),
                ('apparent_age', models.PositiveIntegerField()),
                ('appearence', models.TextField()),
                ('distinguishing_features', models.TextField()),
                ('history', models.TextField()),
                ('notes', models.TextField()),
                ('is_vampire', models.BooleanField(default=True)),
                ('blood_potency', models.PositiveSmallIntegerField()),
                ('predator_type', models.CharField(max_length=50)),
                ('hunger', models.PositiveSmallIntegerField()),
                ('chronicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='chronicle.Chronicle')),
            ],
            options={
                'verbose_name': 'Main Character',
                'verbose_name_plural': 'Main Characters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('minimum_blood_potency', models.PositiveSmallIntegerField()),
                ('maximum_blood_potency', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Generation',
                'verbose_name_plural': 'Generations',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='MinorCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('physical_dice', models.PositiveSmallIntegerField()),
                ('mental_dice', models.PositiveSmallIntegerField()),
                ('social_dice', models.PositiveSmallIntegerField()),
                ('special', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('chronicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minor_characters', to='chronicle.Chronicle')),
            ],
        ),
        migrations.CreateModel(
            name='MinorCharacterWellbeing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_health', models.PositiveSmallIntegerField()),
                ('max_willpower', models.PositiveSmallIntegerField()),
                ('aggravated_health_damage', models.PositiveSmallIntegerField()),
                ('aggravated_willpower_damage', models.PositiveSmallIntegerField()),
                ('superficial_health_damage', models.PositiveSmallIntegerField()),
                ('superficial_willpower_damage', models.PositiveSmallIntegerField()),
                ('health_state', models.CharField(choices=[('DEAD', 'Dead'), ('TORPOR', 'Torpor'), ('IMPAIRED', 'Physically Impaired'), ('INJURED', 'Injured'), ('HEALTHY', 'Ok')], max_length=25)),
                ('willpower_state', models.CharField(choices=[('IMPAIRED', 'Impaired'), ('OK', 'Ok')], max_length=25)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellbeing', to='character.MinorCharacter')),
            ],
            options={
                'verbose_name': 'Minor Character Wellbeing',
                'verbose_name_plural': 'Minor Character Wellbeings',
            },
            bases=(models.Model, character.models.mixins.wellbeing_mixin.WellbeingMixin),
        ),
        migrations.CreateModel(
            name='MinorCharacterExceptionalDice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('value', models.PositiveSmallIntegerField()),
                ('minor_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptional_dice', to='character.MinorCharacter')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinePower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('dice_pools', models.CharField(max_length=50)),
                ('cost', models.TextField()),
                ('system', models.TextField()),
                ('duration', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powers', related_query_name='power', to='character.Character')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Discipline')),
            ],
            options={
                'verbose_name': 'Power',
                'verbose_name_plural': 'Powers',
                'ordering': ['character', 'discipline', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('disciplines', models.ManyToManyField(related_name='clans', to='character.Discipline')),
            ],
            options={
                'verbose_name': 'Vampire Clan',
                'verbose_name_plural': 'Vampire Clans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterWellbeing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_health', models.PositiveSmallIntegerField()),
                ('max_willpower', models.PositiveSmallIntegerField()),
                ('aggravated_health_damage', models.PositiveSmallIntegerField()),
                ('aggravated_willpower_damage', models.PositiveSmallIntegerField()),
                ('superficial_health_damage', models.PositiveSmallIntegerField()),
                ('superficial_willpower_damage', models.PositiveSmallIntegerField()),
                ('health_state', models.CharField(choices=[('DEAD', 'Dead'), ('TORPOR', 'Torpor'), ('IMPAIRED', 'Physically Impaired'), ('INJURED', 'Injured'), ('HEALTHY', 'Ok')], max_length=25)),
                ('willpower_state', models.CharField(choices=[('IMPAIRED', 'Impaired'), ('OK', 'Ok')], max_length=25)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellbeing', to='character.Character')),
            ],
            options={
                'verbose_name': 'Character Wellbeing',
                'verbose_name_plural': 'Character Wellbeings',
            },
            bases=(models.Model, character.models.mixins.wellbeing_mixin.WellbeingMixin),
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Physical'), (1, 'Social'), (2, 'Mental')])),
                ('speciality', models.CharField(blank=True, max_length=50)),
                ('value', models.PositiveSmallIntegerField(choices=[(0, 'Untrained'), (1, 'Novice'), (2, 'Trained'), (3, 'Experienced'), (4, 'Expert'), (5, 'Renowned Master')])),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='character.Character')),
            ],
            options={
                'verbose_name': 'Character Skill',
                'verbose_name_plural': 'Character Skills',
                'ordering': ['character', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterRitual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('ritual_level', models.PositiveSmallIntegerField()),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('process', models.TextField(blank=True, null=True)),
                ('system', models.TextField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rituals', to='character.Character')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='character.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(choices=[(0, 'Latent'), (1, 'Nascent'), (2, 'Developing'), (3, 'Potent'), (4, 'Masterful'), (5, 'Apotheosis')])),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Character')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Physical'), (1, 'Social'), (2, 'Mental')])),
                ('display_order', models.PositiveSmallIntegerField()),
                ('value', models.PositiveSmallIntegerField(choices=[(0, 'Debilitated'), (1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Excellent'), (5, 'Peak Ability')])),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='character.Character')),
            ],
            options={
                'verbose_name': 'Character Skill',
                'verbose_name_plural': 'Character Skills',
                'ordering': ['character', 'category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='clan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='character.Clan'),
        ),
        migrations.AddField(
            model_name='character',
            name='generation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='character.Generation'),
        ),
    ]
