
HEALTH_STATE_DEAD = "DEAD"
HEALTH_STATE_TORPOR = "TORPOR"
HEALTH_STATE_IMPAIRED = "IMPAIRED"
HEALTH_STATE_INJURED = "INJURED"
HEALTH_STATE_HEALTHY = "HEALTHY"

HEALTH_STATES = (
    (HEALTH_STATE_DEAD, "Dead"),
    (HEALTH_STATE_TORPOR, "Torpor"),
    (HEALTH_STATE_IMPAIRED, "Physically Impaired"),
    (HEALTH_STATE_INJURED, "Injured"),
    (HEALTH_STATE_HEALTHY, "Ok"),
)

WILLPOWER_STATE_IMPAIRED = "IMPAIRED"
WILLPOWER_STATE_HEALTHY = "OK"

WILLPOWER_STATES = (
    (WILLPOWER_STATE_IMPAIRED, "Impaired"),
    (WILLPOWER_STATE_HEALTHY, "Ok")
)