
HEALTH_STATE_DEAD = -1
HEALTH_STATE_TORPOR = 0
HEALTH_STATE_IMPARED = 1
HEALTH_STATE_INJURED = 2
HEALTH_STATE_HEALTHY = 3

HEALTH_STATES = (
    (HEALTH_STATE_DEAD, "Dead"),
    (HEALTH_STATE_TORPOR, "Torpor"),
    (HEALTH_STATE_IMPARED, "Physically Impared"),
    (HEALTH_STATE_INJURED, "Injured"),
    (HEALTH_STATE_HEALTHY, "Healthy"),
)

WILLPOWER_STATE_IMPARED = 0
WILLPOWER_STATE_OK = 1

WILLPOWER_STATES = (
    (WILLPOWER_STATE_IMPARED, "Impared"),
    (WILLPOWER_STATE_OK, "Unimpared")
)